trigger:
- main

pool:
  name: 'default'
  demands:
    - Agent.Name -equals Muneer

variables:
  # ACR service connection and registry details – update these to match your environment.
  dockerRegistryServiceConnection: 'ACR'
  dockerRegistry: 'mycontainerregistry788.azurecr.io'
  tag: '111'
  
  # Define image repository names for each service.
  imageRepositoryCatalog: 'eshop/catalog-api'
  imageRepositoryOrdering: 'eshop/ordering-api'
  imageRepositoryBasket: 'eshop/basket-api'
  imageRepositoryIdentity: 'eshop/identity-api'
  imageRepositoryPayment: 'eshop/payment-api'
  imageRepositoryWebhooks: 'eshop/webhooks-api'
  imageRepositoryMobileBff: 'eshop/mobile-bff'
  imageRepositoryWebBff: 'eshop/web-bff'
stages:
  - 