trigger:
- main

pool:
  name: 'default'
  demands:
    - Agent.Name -equals Muneer

  vmImage: 'ubuntu-latest'

variables:
  acrName: 'mycontainerregistry788'
  acrLoginServer: 'mycontainerregistry788.azurecr.io'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mycontainerregistry788'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
